name: admin_app
description: "Admin panel for 행정도우미"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  go_router: ^16.1.0
  http: ^1.1.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  csv: ^6.0.0
  file_picker: ^10.3.1
  supabase_flutter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true